#!/bin/sh
## bootstrap for 42sh
##
## Made by Seblu
## Login   <seblu@epita.fr>
##
## Started on  Sun Jul 16 19:43:53 2006 Seblu
## Last update Thu Nov 23 14:44:19 2006 seblu
##

# Failures do matter.
set -e

# See what i'am doing
set -x

# install the GNU Build System.
autoreconf -i -f -v
