.TH 42sh 1 "2006 jan 21"
.SH NAME
42sh \- The 42 Shell
.SH SYNOPSIS
\fB42sh\fP [options] [file]
.SH DESCRIPTION
42sh is a complete implementation of a standard shell.
.SS Options
option petace
.TP
\fB-c\fP
Cafe chaud
.SH FILES
.TP
\fI~/.42shrc\fP
The personal initialization file
.TP
\fI/etc/42shrc\fP
The systemwide initialization file
.SH AUTHORS
Sebastien LUTTRINGER
.br
seblu@seblu.net
.SH "SEE ALSO"
bash (1)